"""
Dataset validator.

Validates a parsed DataFrame against a schema from contracts/dataset_schemas.py.
Returns a structured ValidationResult — never raises for validation failures.

⚠️  IMPORT RESTRICTION: No imports from ui/, database/, or pipelines/.
"""
from dataclasses import dataclass, field
import pandas as pd

from contracts.dataset_schemas import get_schema


@dataclass
class ValidationResult:
    """Structured validation result."""
    is_valid: bool
    dataset_type: str
    row_count: int
    column_count: int
    label_column: str | None
    unique_labels: list[str] = field(default_factory=list)
    missing_columns: list[str] = field(default_factory=list)
    extra_columns: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


def validate_dataset(df: pd.DataFrame, dataset_type: str, *,
                     schema: dict | None = None) -> ValidationResult:
    """
    Validate a DataFrame against a dataset schema.

    Steps:
      1. Look up schema via get_schema()
      2. If unknown dataset_type → invalid
      3. Compare columns: find missing and extra
      4. Missing columns → invalid (pipeline will break)
      5. Extra columns → warning only (allow supersets)
      6. Empty DataFrame → invalid
      7. Check label column exists, extract unique labels

    Args:
        df: Parsed DataFrame (headers already stripped).
        dataset_type: e.g. "HIKARI2021".
        schema: OPSIONAL. Skema yang sudah diselesaikan pemanggil.
            Modul ini tidak boleh mengimpor ``database/`` (lihat batasan
            impor di atas), sementara skema research pipeline TERUNGGAH
            hanya ada di basis data. Jadi pemanggil yang memang boleh
            membacanya (``orchestrator/validation_service.py``) yang
            menyodorkannya ke sini. Tanpa itu, pencarian statis dipakai
            seperti sebelumnya — perilaku pemanggil lama tidak berubah
            sama sekali.

    Returns:
        ValidationResult with all fields populated.
    """
    if schema is None:
        schema = get_schema(dataset_type)

    if schema is None:
        return ValidationResult(
            is_valid=False,
            dataset_type=dataset_type,
            row_count=len(df),
            column_count=len(df.columns),
            label_column=None,
            errors=[f"Unknown dataset type: {dataset_type}"],
        )

    # JSON-format datasets (e.g. EVE_SURICATA): columns are generated by pipeline phases,
    # not present in the raw file. Validate top-level JSON keys instead.
    if schema.get("file_format") in ("json", "json_or_csv"):
        expected_keys = set(schema.get("expected_top_level_keys", []))
        actual_base = set(c.split(".")[0] for c in df.columns.tolist())
        missing_keys = sorted(expected_keys - actual_base)
        errors = []
        if missing_keys:
            errors.append(f"Missing expected JSON keys: {missing_keys}")
        if len(df) == 0:
            errors.append("DataFrame is empty (0 rows)")
        return ValidationResult(
            is_valid=len(errors) == 0,
            dataset_type=dataset_type,
            row_count=len(df),
            column_count=len(df.columns),
            label_column=schema["label_column"],
            unique_labels=[],  # labels are synthesized later by pipeline phases
            missing_columns=[],
            extra_columns=[],
            errors=errors,
        )

    expected = set(schema["expected_columns"])
    actual = set(df.columns.tolist())

    missing = sorted(expected - actual)
    extra = sorted(actual - expected)

    errors = []

    if missing:
        errors.append(f"Missing required columns: {missing}")

    if len(df) == 0:
        errors.append("DataFrame is empty (0 rows)")

    label_col = schema["label_column"]
    unique_labels = []

    if label_col in df.columns:
        unique_labels = sorted(df[label_col].dropna().unique().tolist())
    elif label_col not in missing:
        errors.append(f"Label column '{label_col}' not found")

    return ValidationResult(
        is_valid=len(errors) == 0,
        dataset_type=dataset_type,
        row_count=len(df),
        column_count=len(df.columns),
        label_column=label_col if label_col in df.columns else None,
        unique_labels=unique_labels,
        missing_columns=missing,
        extra_columns=extra,
        errors=errors,
    )
